services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  psx-tracker:
    build: .
    container_name: python_psx_tracker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
volumes:
  db_data:
        